config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    root to: 'homes#top'
    get "/about" => "homes#about"

  end




  scope module: :public do
    resource :customers, except: [:show, :create]
    resources :items, only: [:index, :show]
    resources :addresses
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete"  => "orders#complete"
    resources :orders

    root to: 'homes#top'
    get "/about" => "homes#about"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"

  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_active == true)
  # end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

     if @customer.update(customer_params)
        flash[:notice] = "更新しました。"
        redirect_to admin_customer_path(@customer.id)
     else
        render :edit
     end
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.

  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :reject_customer, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_paramss
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_active == true)
        flash[:notice] = "退会済みです。再度ご登録ください。"
        redirect_to new_customer_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end

  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-md-2">
     <div><h4>会員情報編集</h4></div></br >
    </div>
   </div>

   <div class="row">
    <div class="col-6">

    <%= form_with model:@customer, url:admin_customer_path(@customer.id), local:true do |f| %>
    <table style="border:none;">
     <tr>
      <th width="180">会員ID</th>
      <td><%= @customer.id %></td>
      <td></td>
     </tr>

     <tr>
      <th>氏名</th>
      <td><%= f.text_field :last_name, class:"form-control customer_last_name" %></td>
      <td><div><%= f.text_field :first_name, class:"form-control customer_first_name" %></div></td>
     </tr>

     <tr>
      <th>フリガナ</th>
      <td><%= f.text_field :last_name_kana, class:"form-control customer_last_name_kana" %></td>
      <td><%= f.text_field :first_name_kana, class:"form-control customer_first_name_kana" %></td>
     </tr>

     <tr>
      <th>郵便番号</th>
      <td><%= f.text_field :postal_code, class:"form-control customer_postal_code" %></td>
     </tr>

     <tr>
      <th>住所</th>
      <td><%= f.text_field :address, class:"form-control customer_address" %></td>
     </tr>

     <tr>
      <th>電話番号</th>
      <td><%= f.text_field :telephone_number, class:"form-control customer_telephone_number" %></td>
     </tr>

     <tr>
      <th>メールアドレス</th>
      <td><%= f.text_field :email, class:"form-control customer_email" %></td>
     </tr>

     <tr>
      <th>会員ステータス</th>
      <td>
       <%= f.radio_button :is_active, "false" %>
       <%= f.label :is_active, "有効" %>

       <%= f.radio_button :is_active, "true" %>
       <%= f.label :is_active, "無効" %>

      </td>
     </tr>

     <tr>
      <th></th>
      <td><div  class="my-4"><%= f.submit '変更を保存', class:"btn btn-sm btn-primary" %></div></td>
     </tr>
    </table>
    <% end %>

   </div>
  </div>

  </div>
 </main>

app/views/admin/customers/index.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-md-2">

     <div><h4>会員一覧</h4></div></br >
    </div>
   </div>

   <div class="row">
     <div class="col-md-8">

       <table class="table">
         <thead class="thead-light">
             <th>会員ID</th>
             <th>氏名</th>
             <th>メールアドレス</th>
             <th>会員ステータス</th>
         </thead>
         <% @customers.each do |customer| %>
         <tbody>
           <tr>
             <td><%= customer.id %></td>
             <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><span class="mx-2"><%= customer.first_name %></span><% end %></td>
             <td><%= customer.email %></td>
             <td>
              <% if customer.is_active %>
               退会
              <% else %>
               有効
              <% end %>
             </td>
           </tr>
         </tbody>
         <% end %>
       </table>
     </div>
   </div>

  </div>
</main>

app/views/admin/customers/show.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-4">

     <div><h4><%= @customer.last_name %>さんの会員詳細</h4></div></br >
    </div>
   </div>

   <div class="row">
    <div class="col-6">

    <table style="border:none;">
     <tr>
      <th width="180">会員ID</th>
      <td><%= @customer.id %></td>
     </tr>

     <tr>
      <th>氏名</th>
      <td><span><%= @customer.last_name %></span><span class="mx-2"><%= @customer.first_name %></span></td>
     </tr>

     <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana %><span class="mx-2"><%= @customer.first_name_kana %></span></td>
     </tr>

     <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
     </tr>

     <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
     </tr>

     <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
     </tr>

     <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
     </tr>

     <tr>
      <th>会員ステータス</th>
      <td>
       <% if @customer.is_active %>
        退会
       <% else %>
        有効
       <% end %>
      </td>
     </tr>
    </table>
   </div>
  </div>

   <div class="row">
    <div class="col-8 my-4">
     <%=link_to "編集する", edit_admin_customer_path(@customer.id),class: 'btn btn-sm btn-primary'%>
     <span class="mx-5"><%=link_to "注文一覧を見る",admin_root_path, class: 'btn btn-sm btn-primary'%></span>
    </div>
   </div>




  </div>
 </main>