config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    root to: 'homes#top'
    get "/about" => "homes#about"

  end




  scope module: :public do
    resource :customers, except: [:show, :create]
    resources :items, only: [:index, :show]
    resources :addresses
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete"  => "orders#complete"
    resources :orders

    root to: 'homes#top'
    get "/about" => "homes#about"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"

  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :customer

    validates :name, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true

    def full_address
        '〒' + postal_code + ' ' + address + ' ' + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_active == true)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy

    attachment :image

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :cart_items, dependent: :destroy
    has_many :oder_details, dependent: :destroy
    belongs_to :genre

    attachment :image

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    validates :is_active, presence: true

    def with_tax_price
     (price * 1.1).floor
    end

end

app/models/oder_detail.rb
class OderDetail < ApplicationRecord

    belongs_to :order
    belongs_to :item

    enum status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3,
    }

end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_details, dependent: :destroy

    enum payment_method: { credit_card: 0, transfer: 1 }

    enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4,
    }

    def with_tax_price
     (price * 1.1).floor
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

    belongs_to :order
    belongs_to :item

    enum making_status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3,
    }

    def with_tax_price
     (price * 1.1).floor
    end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
     if @genre.update(genre_params)
        flash[:notice] = "更新しました。"
        redirect_to admin_genres_path
     else
        render :edit
     end

  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def top
  @orders = Order.all
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    @item.genre_id = params[:item][:genre_id]

    if @item.save
       flash[:notice] = "商品を登録しました。"
       redirect_to admin_item_path(@item.id)
    else
      # @items = Item.all
       render :new
    end
  end


  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
       flash[:notice] = "更新できました."
       redirect_to admin_item_path(@item.id)
    else
       render :edit
    end
  end

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def show
  @order = Order.find(params[:id])
  @order_details = OrderDetail.all

 end

 def update
  @order = Order.find(params[:id])
  @order.order_detail

   if @order.update(order_params)
      flash[:notice] = "更新しました"
      redirect_to admin_order_path(@order.id)
   else
      render :show
   end
 end


 private
 def order_params
  params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

# ログアウト後の遷移
  private

    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope == :customer
            root_path
        elsif resource_or_scope == :admin
            admin_root_path
        else
            root_path
        end
    end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :customer
            root_path
        elsif resource_or_scope == :admin
            new_admin_session_path
        else
            root_path
        end
    end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/genres/edit.html.erb
<br>
 <main>
   <div class="container", align="center">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-4 px-5 px-sm-10">

      	 <% if @genre.errors.any? %>
      　  <%= @genre.errors.count %>error prohibited this obj from being saved:
         <% @genre.errors.full_messages.each do |message| %>
         <%= message %>
         <% end %>
         <% end %>

        <table style="border:none;" width="500">
         <thread>
           <tr>
             <th><h5>ジャンル編集</h5></th>

             <%= form_with model:@genre, url:admin_genre_path, local:true do |f| %>
             <div class="form-group">
               <th><%= f.text_field :name %></th>
             </div>
             <th><%= f.submit '編集', url:admin_genres_path, class: "btn btn-sm btn-primary" %></th>
            <% end %>

           </tr>
         </thread>
        </table>
      </div>
    </div>
   </div>
  </main>

app/views/admin/genres/index.html.erb
<br>
 <main>
   <div class="container", align="center">
    <div class="row">
      <div class="col-3">
      	<h4>ジャンル一覧・追加</h4><br>
      </div>
    </div>

      <div class="row">
        <div class="col-6">
          <table style="border:none;" width="400">
            <thead>
             <tr>
               <th><h6>ジャンル名</h6></th>

               <%= form_with model:@genre, url:admin_genres_path, local:true do |f| %>
                <div class="form-group">
                  <th><%= f.text_field :name %></th>
                </div>

               <th><%= f.submit '新規登録', class: "btn btn-sm btn-primary" %></th>
               <% end %>

             </tr>
            </thead>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-4">
         <div class="ml-5">
          <table class="table">
            <thead class="thead-light">
               <tr>
                 <th>ジャンル</th>
                 <th></th>
               </tr>
             </thead>

               <tbody>
                <% @genres.each do |genre| %>
                 <tr>
                   <td>
                     <span><%= genre.name %></span>
                   </td>
                   <td>
                     <span><%=link_to "編集", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-primary" %></span>
                   </td>
                 </tr>
      　　　　　<% end %>
               </tbody>
          </table>
         </div>
        </div>
      </div>

  </div>
 </main>

app/views/admin/items/edit.html.erb
<br>
<main>
  <div class="container", align="center">
   <%= form_with model:@item, url:admin_item_path(@item.id), local:true do |f| %>

   <div class="row">
    <div class="col-2">

      <% if @item.errors.any? %>
      <%= @item.errors.count %>エラーが発生しました:
      <% @item.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>

     <div><h4>商品編集</h4></div></br >
    </div>
   </div>

   <div class="row">
   <div class="col-6">
    <table style="border:none">
     <thead>

      <tr>

       <th><h6>商品画像</h6></th>
     　<th><%= f.attachment_field :image, class:"form-control-file image", placeholder:"商品画像" %></th>
     　</tr>

     　 <tr>
       <th><h6>商品名</h6></th>
       <th><%= f.text_field :name, class:"form-control item_name" %></th>
       </tr>

       <tr>
       <th><h6>商品説明</h6></th>
       <th><%= f.text_area :introduction, class:"form-control item_introduction" %></th>
       </tr>

       <tr>
       <th><h6>ジャンル</h6></th>
       <th><%= f.collection_select :genre_id, @genres, :id, :name, { include_blank: '-選択してください-' }, { class: 'form-control' , required: true } %></th>
       </tr>

       <tr>
       <th><h6>税込価格</h6></th>
       <th><%= f.text_field :price, class:"form-control item_price" %></th>
       </tr>

       <tr>
       <th><h6>販売ステータス</h6></th>
       <th><%= f.select :is_active, {'販売中': 1, '販売停止中': 2}, { include_blank: '-選択してください-' }, { class: 'form-control' , required: true } %></th>
       </tr>

     </thead>
    </table>
   </div>
   </div>

   <div class="row" >
    <div class="col-6", class="text-center" >
   　<br><%= f.submit '変更を保存', class:"btn btn-sm btn-primary" %>
    </div>
   </div>

    <% end %>

  </div>
</main>

app/views/admin/items/index.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-lg-2">

     <div><h4>商品一覧</h4></div></br >
    </div>
   </div>

   <div class="row">
    <div class="col-2">
     <tr><div class="mb-2"><%= link_to "商品追加", new_admin_item_path, class:"btn btn-sm btn-primary" %></div></tr>
    </div>
   </div>

   <div class="row">
     <div class="col-lg-10">
       <table class="table">
         <thead class="thead-light">
           <tr>
             <th>商品ID</th>
             <th>商品名</th>
             <th>税抜価格</th>
             <th>ジャンル</th>
             <th>ステータス</th>
           </tr>
         </thead>
         <tbody>
          <% @items.each do |item| %>
           <tr>
             <td width="100">
               <%= item.id %>
             </td>
             <td width="220">
               <%= link_to admin_item_path(item.id) do %><%= item.name %><% end %>
             </td>
             <td width="120">
               <%= item.price %>円
             </td>
             <td width="150">
               <%= item.genre.name %>
             </td>
             <td width="130">
              <% if item.is_active %>
               販売中
              <% else %>
               販売停止中
              <% end %>
             </td>
           </tr>
         </tbody>
         <% end %>
       </table>
      </div>
     </div>

   <!--<div class="row" >-->
   <!--  <div class="col-lg-7">-->
   <!--   <div class="pagination">-->
   <!--    <p style='margin: 10px'>1</p>-->
   <!--    <p style='margin: 10px'>2</p>-->
   <!--    <p style='margin: 10px'>3</p>-->
   <!--    <p style='margin: 10px'>Next></p>-->
   <!--    <p style='margin: 10px'>Last>></p>-->
   <!--   </div>-->
   <!--  </div>-->
   <!-- </div>-->

  </div>
</main>

app/views/admin/items/new.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-log-2">

     <div><h4>商品新規登録</h4></div>
    </div>
   </div>

      <% if @item.errors.any? %>
      <%= @item.errors.count %>エラーが発生しました:
      <% @item.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <% end %>

  <div class="row">
   <%= form_with model:@item, url:admin_items_path, local:true do |f| %>

      <div class="col-log-6">
        <table style="border:none">
         <thead>
          <tr>
            <th><h6>商品画像</h6></th>

             <th><%= f.attachment_field :image, class:"form-control-file image", placeholder:"商品画像" %></th>
          </tr>
          <tr>
            <th><h6>商品名</h6></th>
                <th><%= f.text_field :name %></th>
          </tr>
          <tr>
            <th><h6>商品説明</h6></th>
              <th><%= f.text_area :introduction %></th>
          </tr>

          <tr>
            <th><h6>ジャンル</h6></th>
            　<th><%= f.collection_select :genre_id, @genres, :id, :name, { include_blank: '-選択してください-' }, { class: 'form-control' , required: true } %></th>
          </tr>

          <tr>
           <th><h6>税抜価格</h6></th>
            <th><%= f.text_field :price %></th>
          </tr>

          <tr>
            <th><h6>販売ステータス</h6></th>
            <th><%= f.select :is_active, {'販売中': 1, '販売停止中': 2}, { include_blank: '-選択してください-' }, { class: 'form-control' , required: true } %></th>
          </tr>

         </thead>
        </table>
      </div>


    <div class="row", align="center">
     <div class="col-md-8" >
      <th><h3><%= f.submit '新規登録', class: "btn btn-sm btn-primary" %></h3></th>
     </div>
    </div>
  <% end %>
   </div>

  </div>
</main>

app/views/admin/items/show.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-md-2">

     <% if @item.errors.any? %>
     <%= @item.errors.count %>error prohibited this obj from being saved:
     <% @item.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>

     <div><h4>商品詳細</h4></div></br >
    </div>
   </div>

   <div class="row">
    <div class="col-3">
     <%=attachment_image_tag @item, :image, size: '240x180', fallback: "no_image.jpg" %>
    </div>

    <div class="col-4">
      <table style="border:none">
        <thead>
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>

          <tr>
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>

          <tr>
            <th>ジャンル</th>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
            <th>税込価格<br>(税抜価格)</th>
            <td><%= @item.price %>円</td>
          </tr>

          <tr>
            <th><div class="mr-4">販売ステータス</div></th>
            <td>
              <% if @item.is_active %>
               販売中
              <% else %>
               販売停止中
              <% end %>
            </td>
          </tr>

          <tr>
            <th> </th>
            <th> </th>
          </tr>

          <tr>
            <th></th>
            <th><div class="mt-2"><h4><%= link_to "編集する", edit_admin_item_path(@item.id) , class:"btn btn-sm btn-primary" %></h4></div></th>
          </tr>
        </thead>
      </table>
    </div>
   </div>

  </div>
</main>

app/views/admin/orders/show.html.erb
<br>
<main>
  <div class="container", align="center">
   <div class="row">
    <div class="col-2">

     <div><h4>注文履歴詳細</h4></div></br >
    </div>
   </div>

   <div class="row">
    <div class="col-5">
     <table style="border:none" width="400">
      <thead>
        <tr>
          <th>購入者</th>
          <td><%= @order.name %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.to_s(:datetime_jp) %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %><br><%= @order.address %></td>
        </tr>
        <tr>
         <!--<%#= form_with model: @order, url:admin_order_path, method: :patch, locale: true do |f| %>-->
         <!-- <th><div class="mr-3">注文ステータス</th></div>-->
         <!-- <td>-->
         <!--  <%#= f.select :status, [["入金待ち", 0 ], ["入金確認", 1 ], ["発送準備中", 2 ], ["発送済み", 3 ]], :selected=>@order.status %>-->
         <!--  <%#= f.submit "更新", class: "btn btn-sm btn-primary btn-lg" %>-->
         <!-- </td>-->
         <!-- <%# end %>-->
        </tr>
      </thead>
     </table>
    </div>
   </div>
   <br>

   <div class="row">
    <div class="col-6">
     <table class="table">
      <thead class="thead-light">
        <th><div>商品名</div></th>
        <th><div>単価(税込)</div></th>
        <th>数量</th>
        <th>小計</th>
        <!--<th>製作ステータス</th>-->
        <th></th>
      </thead>

      <% @order.order_details.each do |order_detail| %>
      <tbody>
       <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price %>円</td>
        <td><%= order_detail.amount %></td>
        <td><%= order_detail.price %>円</td>
        <!--<td>-->
         <%#= form_with model: @order.order_details, url:admin_order_detail, locale: true do |f| %>
         <%#= f.select :status, [["製作不可", 0 ], ["製作待ち", 1 ], ["製作中", 2 ], ["製作完了", 3 ]], :selected=>@order.order_detail.status %>
        <!--</td>-->
        <%#= f.submit "更新", class: "btn btn-sm btn-primary btn-lg" %>
         <%# end %>
       </tr>
      </tbody>
      <% end %>
     </table>
    </div>

    <div class="col-3 mt-5">
     <table style="border:none">
       <thead>
         <tr>
           <th><strong>商品合計</strong></th>
           <td><%= @order.total_payment %>円</td>
         </tr>
         <tr>
           <th><strong>送料</strong></th>
           <td><%= @order.shipping_cost %>円</td>
         </tr>
         <tr>
           <th><div class="mr-2"><strong>請求金額合計</strong></div></th>
           <td><%= @order.total_payment +  @order.shipping_cost %>円</td>
         </tr>
       </thead>
     </table>
    </div>


 </div>
</main>