config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    root to: 'homes#top'
    get "/about" => "homes#about"

  end




  scope module: :public do
    resource :customers, except: [:show, :create]
    resources :items, only: [:index, :show]
    resources :addresses
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete"  => "orders#complete"
    resources :orders

    root to: 'homes#top'
    get "/about" => "homes#about"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"

  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :customer

    validates :name, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true

    def full_address
        '〒' + postal_code + ' ' + address + ' ' + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_active == true)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy

    attachment :image

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :cart_items, dependent: :destroy
    has_many :oder_details, dependent: :destroy
    belongs_to :genre

    attachment :image

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    validates :is_active, presence: true

    def with_tax_price
     (price * 1.1).floor
    end

end

app/models/oder_detail.rb
class OderDetail < ApplicationRecord

    belongs_to :order
    belongs_to :item

    enum status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3,
    }

end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    has_many :order_details, dependent: :destroy

    enum payment_method: { credit_card: 0, transfer: 1 }

    enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4,
    }

    def with_tax_price
     (price * 1.1).floor
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

    belongs_to :order
    belongs_to :item

    enum making_status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3,
    }

    def with_tax_price
     (price * 1.1).floor
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def top
  @orders = Order.all
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    @item.genre_id = params[:item][:genre_id]

    if @item.save
       flash[:notice] = "商品を登録しました。"
       redirect_to admin_item_path(@item.id)
    else
      # @items = Item.all
       render :new
    end
  end


  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
       flash[:notice] = "更新できました."
       redirect_to admin_item_path(@item.id)
    else
       render :edit
    end
  end

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

# ログアウト後の遷移
  private

    def after_sign_in_path_for(resource_or_scope)
        if resource_or_scope == :customer
            root_path
        elsif resource_or_scope == :admin
            admin_root_path
        else
            root_path
        end
    end

    def after_sign_out_path_for(resource_or_scope)
        if resource_or_scope == :customer
            root_path
        elsif resource_or_scope == :admin
            new_admin_session_path
        else
            root_path
        end
    end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-white bg-dark">
      <div class="container">
       <ul class="navbar-nav ml-auto">

    <% if admin_signed_in? %>

            <li>
             <%= link_to "商品一覧", admin_items_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
             <%= link_to "会員一覧", admin_customers_path,  class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
             <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
             <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
             <%= link_to "ログアウト", destroy_admin_session_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px', method: :delete %>
            </li>

      <% elsif customer_signed_in? %>
            <li>
              <%= link_to "マイページ", customers_my_page_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "カート", cart_items_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px', method: :delete %>
            </li>

     <% else %>
          <li>
              <%= link_to "About", about_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-default btn-lg btn-block', class: 'btn btn-outline-info', style: 'margin: 15px' %>
            </li>


    <% end %>

       </ul>
      </div>
     </nav>
    </header>

    <%= notice %>
    <%= yield %>
  </body>
</html>